BlockModule Update
TorchAPI/Essentials pull request #138
Opened 2019-11-23 02:04 UTC by N1Ran

allows block module to target specific grid by player name or id, grid name/id, or faction tag/id

2019-11-25 02:00 UTC, Jimmacle requested changes
I commented on some things I think should be improved in terms of readability, it would also be nice to see some more comments (I'm not being a hypocrite, I swear)

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
> +                    if (!block.BlockDefinition.Id.TypeId.ToString().Substring(16)
Condition is too long IMO, put it in a variable. Also, put continue on its own line

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
> +            var mehCount = 0;
Should be a more descriptive name

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
> +                var count = grid.GetBlocks().Select(block => block.BlockDefinition.Id.TypeId.ToString().Substring(16)).Count(blockType => string.Compare(type, blockType, StringComparison.InvariantCul
For the love of Clang why (use a foreach and counter instead of the linq, it's too long to read easily)

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
> +            if (Context?.Player?.SteamUserId > 0)
Context will never be null

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
> +        public void CountSubtype(string subtype, string target = null)
Same things commented in CountType apply here

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
>                  Context.Respond($"{category} is not a valid category. Use one of the following: " + string.Join(", ", Enum.GetValues(typeof(BlockCategory))));
Don't mix interpolation and concat, put the `string.Join` in a local and interpolate that

2019-11-25 02:00 UTC, Jimmacle commented on Essentials/Commands/BlocksModule.cs
>                      throw new InvalidBranchException();
I don't think throwing InvalidBranchException is appropriate here, throw an ArgumentException instead with a descriptive message

2019-11-28 14:29 UTC, N1Ran commented
edits submitted

2019-11-30 04:41 UTC, 5Dev24 commented
beans

2019-12-13 23:58 UTC, N1Ran commented
yeeted the comments

2019-12-13 23:59 UTC, Jimmacle approved these changes

2019-12-13 23:59 UTC, merged