Added a few more convenience commands
TorchAPI/Essentials pull request #139
Opened 2019-11-23 19:39 UTC by LordTylus

Since we already had a tpto command I thought it may be useful to also have tphere command. 

A thing I want to try to change however is dealing with players that are seated in the cockpit. Which currently I have not done. Its nice to be able to tp grids or to grids, but if you want to tp to a player inside a grid its still broken :-(

There also now is a command to eject a given player from any seat. Since we had instances on our server where a player was stuck he had to disconnect so we could delete his character from the game and then he could reconnect. An eject command shall improve that. However as everything with essentials it wont work with offline players.

Same goes for the new kill command.

Since you cannot eject offline players we also now have a grids ejectall command where you can either call it by passing a gridname or like my ALE plugins by looking at them. 

The GridFinder is a copy from my ALE Core

2019-11-23 19:47 UTC, N1Ran approved these changes
looks good to me

2019-11-24 17:27 UTC, LordTylus commented
Seems like eject and kill are already present and need some improvements. Which I now did. Please reevaluate

2019-11-24 17:35 UTC, LordTylus commented on Essentials/Commands/EntityModule.cs
> +                        controller.Use();
I have not tested if RemoveUsers works fine or not. Use seems to do the job very well for what I have Tested in my previous commit. So I did not see a reason to revert it back to RemoveUsers.

2019-11-25 02:30 UTC, Jimmacle requested changes
Overall good, I appreciate the commenting. There are just a few style things to change to stay consistent with the rest of the code

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/Commands/EntityModule.cs
> +                } else {
Put braces on their own lines to keep styling consistent

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/GridFinder.cs
> +            ConcurrentBag<MyGroups<MyCubeGrid, MyGridPhysicalGroupData>.Group> groups = new ConcurrentBag<MyGroups<MyCubeGrid, MyGridPhysicalGroupData>.Group>();
Use var for declarations where the type is obvious from the assignment so lines don't get too long

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/GridFinder.cs
> +namespace ALE_Core.Utils {
The bracket style is inconsistent with the rest of the Torch codebase, I'd also prefer this to be in an Essentials namespace

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/GridFinder.cs
> +            foreach (var group in MyCubeGridGroups.Static.Physical.Groups) {
See if you can reduce the nesting here by inverting conditionals, it gets pretty deep for my liking

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/Commands/PlayerModule.cs
> +        [Command("tphere", "Teleport an other entity directly to you.")]
another

2019-11-25 02:30 UTC, Jimmacle commented on Essentials/Commands/GridModule.cs
> +
Only use blank lines when separating logical sections within a block and keep it to one line of whitespace at most

2019-11-26 07:27 UTC, Jimmacle approved these changes

2019-11-26 07:28 UTC, merged